apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        type: database-pod
    spec:
      containers:
        - name: db
          image: dockersamples/k8s-wordsmith-db
          ports:
            - containerPort: 5432