apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: myApi
    type: applicationProgrammingInterface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myApi
  template:
    metadata:
      labels:
        app: myApi
        type: api-pod
    spec:
      containers:
        - name: myapi-pod
          image: dockersamples/k8s-wordsmith-api
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: example
            - name: DB_NAME
              value: words