apiVersion: v1
kind: Service
metadata:
  name: clusterip-db
  labels:
    app: myClusterIp_db
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: mydb
    type: database