apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: myApi
    type: applicationProgrammingInterface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myApi
  template:
    metadata:
      labels:
        app: myApi
        type: api-pod
    spec:
      containers:
        - name: myApi-pod
          image: dockersamples/k8s-wordsmith-api
          ports:
            - containerPort: 8080