apiVersion: v1
kind: Service
metadata:
  name: clusterIp_api
  labels:
    app: myClusterIp_api
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: myApi
    type: applicationProgrammingInterface